import datos, os, pygame

# Imagenes
IMG_Tanque1 = pygame.image.load(os.path.join("Assets", "Tanque1.png"))
IMG_Tanque2 = pygame.image.load(os.path.join("Assets", "Tanque2.png"))
IMG_Tanque3 = pygame.image.load(os.path.join("Assets", "Tanque3.png"))
IMG_Tanque4 = pygame.image.load(os.path.join("Assets", "Tanque4.png"))
IMG_Canon1 = pygame.image.load(os.path.join("Assets", "canon1.png"))
IMG_Canon2 = pygame.image.load(os.path.join("Assets", "canon2.png"))
IMG_Canon3 = pygame.image.load(os.path.join("Assets", "canon3.png"))
IMG_Canon4 = pygame.image.load(os.path.join("Assets", "canon4.png"))
IMG_Background = pygame.image.load(os.path.join("Assets", "background.png"))
IMG_HUD = pygame.image.load(os.path.join("Assets", "hud_bg.png"))
IMG_Explosion = pygame.image.load(os.path.join("Assets", "boom.png"))
IMG_Bala = pygame.image.load(os.path.join("Assets", "bala105.png"))
IMG_Bala60 = pygame.image.load(os.path.join("Assets", "bala60.png"))
IMG_Bala80 = pygame.image.load(os.path.join("Assets", "bala80.png"))
IMG_Bala105 = pygame.image.load(os.path.join("Assets", "bala105.png"))
IMG_Exit = pygame.image.load(os.path.join("Assets", "exit.png"))
IMG_Restart = pygame.image.load(os.path.join("Assets", "reset.png"))

#Reescalado de imagenes
Tanque1 = pygame.transform.scale(IMG_Tanque1, (IMG_Tanque1.get_width() // 4, IMG_Tanque1.get_height() // 4))
Tanque2 = pygame.transform.scale(IMG_Tanque2, (IMG_Tanque2.get_width() // 4, IMG_Tanque2.get_height() // 4))
Canon1 = pygame.transform.scale(IMG_Canon1, (IMG_Canon1.get_width() // 4, IMG_Canon1.get_height() // 4))
Canon2 = pygame.transform.scale(IMG_Canon2, (IMG_Canon2.get_width() // 4, IMG_Canon2.get_height() // 4))
Background = pygame.transform.scale(IMG_Background, (datos.PANT_ANCHO, 540))
HUD = pygame.transform.scale(IMG_HUD, (datos.PANT_ANCHO, 120))    
Tanque1_HUD = pygame.transform.scale(IMG_Tanque1, (IMG_Tanque1.get_width() // 2, IMG_Tanque1.get_height() // 2))
Tanque2_HUD = pygame.transform.scale(IMG_Tanque2, (IMG_Tanque2.get_width() // 2, IMG_Tanque2.get_height() // 2))
Bala105 = pygame.transform.scale(IMG_Bala105, (IMG_Bala105.get_width() // 1.5, IMG_Bala105.get_height() // 1.5))
Bala80 = pygame.transform.scale(IMG_Bala80, (IMG_Bala80.get_width() // 1.75, IMG_Bala80.get_height() // 1.75))
Bala60 = pygame.transform.scale(IMG_Bala60, (IMG_Bala60.get_width() // 2, IMG_Bala60.get_height() // 2))
Explosion = pygame.transform.scale(IMG_Explosion, (IMG_Explosion.get_width() // 4, IMG_Explosion.get_height() // 4))
Exit = pygame.transform.scale(IMG_Exit, (IMG_Exit.get_width() // 1.5, IMG_Exit.get_height() // 1.5))
Restart = pygame.transform.scale(IMG_Restart, (IMG_Restart.get_width() // 1.5, IMG_Restart.get_height() // 1.5))